services:
  plant-service:
    build: . # uses Dockerfile in root dir to build the image
    ports:
      - 8080:8080
  
  plant-test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres # Big THX to Amir.SH!!! for simplifiying DB initialization
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always      
  


  redis:
    image: redis:6.0.6-alpine
    command: redis-server
    ports:
      - 6379:6379